# Generated by Django 6.0.3 on 2026-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0, help_text='Minutes')),
                ('avg_turns_per_session', models.FloatField(default=0.0)),
                ('english_messages', models.IntegerField(default=0)),
                ('arabic_messages', models.IntegerField(default=0)),
                ('arabizi_messages', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('feedback_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Daily Metrics',
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=200)),
                ('avg_response_time_ms', models.FloatField()),
                ('avg_reward_score', models.FloatField(blank=True, null=True)),
                ('total_requests', models.IntegerField()),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
